_for-parents/Holidays and School Closures.md
Need your approval for my pull request.
Thank you.
Rgds,
Razilah
=> Update on the holidays and school closure page 

_for-parents/School Information/Traffic Management Plan.md
Dear Mdm Nithiya, 
Need your approval for my pull request.
Thank you.
Rgds,
Razilah
=> Update on the Traffic Management Plan page

_for-parents/Holidays and School Closures.md, _our-people/School Management Committee/Level Heads (LHs) | Subject Heads (SHs) | Assistant Year Heads (AYHs).md, _our-people/School Management Committee/Senior Teachers.md, _our-people/Teaching Staff/Adjunct Teachers.md, _our-people/Teaching Staff/Teaching Staff.md
I have made some updates to the school website. Please approve my pull request.
Thank you.
Rgd,
Razilah
=> Update on "Our People" page

_highlights/Photos/2023.md
=> Update on the "Highlights" page

_for-parents/Holidays and School Closures.md
=> Update on school holiday closure page

_for-parents/Our Service Providers.md
=> Changes to School Uniform Section

_for-parents/Holidays and School Closures.md
Dear Fizah,
Thank you.
Regards,
Razilah
=> Updates on the "Holiday and School closure" page

_for-parents/Holidays and School Closures.md
I have made some updates to the school website.
Rgds,
Razilah
=> Update on 'Holidays and School Closure' Page

_for-parents/Holidays and School Closures.md
I have made changes to the school website.
Thank you.
Rgds,
Razilah
=> Update to 'Holidays and School Closures' page

_for-parents/New P1 Parents/Administrative Matters.md
There's some minor update to the school website.
Thank you.
Rgds,
Razilah
=> Updates on the 'Administrative Matters' Page

_for-parents/New P1 Parents/Administrative Matters.md, _for-parents/Parents Support Group/Make a Difference @ Concord.md
at point no. 11 Join M.A.D parents
=> update in New P1 Parent Page

_for-parents/New P1 Parents/Administrative Matters.md
I've made updates to the school website.
Thank you.
Rgds,
Razilah
=> Updates to the Administrative Matters page

_for-parents/Holidays and School Closures.md
I've updated the school website.
Thank you.
Rgds,
Razilah
=> Updates on 'Holidays and School Closures' page

_highlights/Photos/2023.md
I've just uploaded Grace Day photos at 'Highlights' Page.
Please approve my request.
Thank you.
Rgds,
Razilah
=> Updates on 'Highlights' page

_for-parents/Holidays and School Closures.md
Hi Fizah,
Please help to review and approve my request.
Thank you.
Rgds,
Razilah
=> Updates to the 'Holidays and school closures' page

_for-parents/School Calendar, Term Notes and Newsletters.md
Created term 2, issue 2 for upper primary parent news letter
=> School Calendar, Term Notes and Newsletters

_for-parents/School Calendar, Term Notes and Newsletters.md
Added 2024 Term 1 Note & Term 2 Note
=> School Calendar, Term Notes and Newsletter

_for-parents/School Calendar, Term Notes and Newsletters.md
removed tabs LP & MP under 2024 newsletter for parent (awaiting documents to upload).
=> school calendar, term note and newsletter 

pages/privacy.md, pages/terms-of-use.md
Updating of Terms of Use and Privacy Statement
=> Updating of Terms of Use and Privacy Statement

_our-people/Executive and Administration Staff (EAS).md
Change in designation and add new staff in EAS group
=> Change in designation and add new staff in EAS group

_our-people/Executive and Administration Staff (EAS).md
Who forgot to add her when the page was created arh?  T_T
=> Addition of Sook Hoon to EAS webpage

_for-parents/MOE ICT Platforms/Students Learning Space (SLS).md
Update Q3 FAQ: change to Mr Suhaimi email address.
=> SLS administrator Update

_for-parents/Holidays and School Closures.md, _highlights/Photos/2024.md
=> Update to Holidays and School Closures

index.md
Notification of school phone is down
=> Notification of school phone is down

index.md
remove notification of phone line distruption
=> remove notification

_programmes/Learning for Life Programme (LLP).md
=> Concord outdoor education-under learning for life programme

pages/Learning Platforms.md
Learning Platforms - added Math Check. Requested by Ms Norishah.
=> Math Check

_about-us/Principal's Message.md
told to remove Principle Mr.Tan's Message.
=> Principle's Message

_our-people/Teaching Staff/Teaching Staff.md
not all have included the moe eamil address, no info
=> Our People: Teaching staffs 2025

_our-people/Teaching Staff/Teaching Staff.md
=> CPS Teaching staffs, form teacher

_our-people/School Management Committee/Head of Departments (HODs) | Year Heads (YHs).md, _our-people/School Management Committee/Level Heads (LHs) | Subject Heads (SHs) | Assistant Year Heads (AYHs).md, _our-people/School Management Committee/Senior Teachers.md, _our-people/Teaching Staff/Adjunct Teachers.md, _our-people/Teaching Staff/Allied Educators (AED)| SEN Officers.md
Upate new per Lisa's list
Adjunct teachers, HOD, YH(LP,MP,UP) AYH , SH and ST
=> Our People

_our-people/School Management Committee/Head of Departments (HODs) | Year Heads (YHs).md, _our-people/School Management Committee/Level Heads (LHs) | Subject Heads (SHs) | Assistant Year Heads (AYHs).md, _our-people/Teaching Staff/Allied Educators (AED)| SEN Officers.md
Remove Mdm Nur Eva (LH Math.), Move Christine Tan to HOD science internal, add Mdm Nurul Hidayah SEN officer
=> Teaching staff (SEN), HOD, YH, upadte

_for-parents/Holidays and School Closures.md
Forgot to update the "Last updated:"
=> School closure dates update

_for-parents/Holidays and School Closures.md
Remove "TBC" from Hari Raya Haji date description.
=> Holidays and School Closures

_for-parents/Our Service Providers.md
=> Removal of Apr Dental dates

_for-parents/Parents Support Group/Make a Difference @ Concord.md
attached new photos replaced old.
=> Parent support group

_departments/Mother Tongue Language.md, pages/Learning Platforms.md
=> Department - MTL -Chinese language
